spark:
  master: "local[*]"
  driver_memory: "18g"
  driver_max_result_size: "4g"
  executor_memory: "2g"
  sql:
    adaptive:
      enabled: true
      coalesce_partitions: true
    arrow_enabled: true
  serializer: "org.apache.spark.serializer.KryoSerializer"

data:
  raw_data_path: "data/raw_data/"
  structured_data_path: "data/structured_data/"
  labelled_data_path: "data/structured_data_labelled/"
  bert_format_path: "data/bert_format/"

models:
  spark_models_path: "models/spark_models/"
  bert_models_path: "models/bert_models/"