# Generated by Django 5.2.8 on 2025-11-17 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('model_type', models.CharField(max_length=10)),
                ('total_logs', models.IntegerField(default=0)),
                ('processed_logs', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('ml_model_loaded', models.BooleanField(default=False)),
                ('dl_model_loaded', models.BooleanField(default=False)),
                ('bert_model_loaded', models.BooleanField(default=False)),
                ('total_requests', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.TextField()),
                ('parsed_content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='anomaly_detector.logsource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('f1_score', models.FloatField()),
                ('balanced_accuracy', models.FloatField()),
                ('auroc', models.FloatField(blank=True, null=True)),
                ('mcc', models.FloatField(blank=True, null=True)),
                ('per_class_metrics', models.JSONField()),
                ('test_source', models.CharField(blank=True, max_length=50)),
                ('test_samples', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['model_type', '-f1_score'], name='anomaly_det_model_t_62d2f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('ml', 'Machine Learning'), ('dl', 'Deep Learning'), ('bert', 'BERT-based')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('predicted_class', models.IntegerField()),
                ('predicted_class_name', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField()),
                ('inference_time_ms', models.FloatField(blank=True, null=True)),
                ('features_used', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='anomaly_detector.logentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['-timestamp'], name='anomaly_det_timesta_6296d2_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['source', '-timestamp'], name='anomaly_det_source__f03ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['-created_at'], name='anomaly_det_created_73c83a_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['predicted_class'], name='anomaly_det_predict_fb9b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model_type'], name='anomaly_det_model_t_5cc08a_idx'),
        ),
    ]
